name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.id_ed25519 }} ec2-user@<98.84.165.163> "
            cd /home/ec2-user/budget_tracker &&
            git pull origin main
          "
